# Generated by Django 3.2.3 on 2021-06-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0016_delete_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('network_id', models.AutoField(primary_key=True, serialize=False)),
                ('network_name', models.CharField(max_length=50)),
                ('network_url', models.CharField(max_length=60)),
                ('network_logo', models.CharField(max_length=200)),
                ('network_plan', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('tv_id', models.AutoField(primary_key=True, serialize=False)),
                ('tv_name', models.CharField(max_length=200)),
                ('tv_slug', models.CharField(max_length=220, null=True, unique=True)),
                ('tv_year', models.IntegerField(max_length=4)),
                ('tv_season', models.IntegerField(null=True)),
                ('tv_rating', models.CharField(max_length=12, null=True)),
                ('tv_imdb', models.CharField(max_length=9, null=True)),
                ('tv_rt', models.CharField(max_length=9, null=True)),
                ('tv_awards', models.CharField(max_length=100, null=True)),
                ('tv_desc', models.TextField(null=True)),
                ('tv_poster', models.CharField(max_length=400)),
                ('tv_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.people')),
            ],
        ),
        migrations.CreateModel(
            name='TVGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvg_genre', models.CharField(max_length=16)),
                ('tvg_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('epi_desc', models.TextField()),
                ('epi_rating', models.CharField(max_length=3, null=True)),
                ('runtime', models.CharField(max_length=15)),
                ('tve_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TVCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvc_char', models.CharField(max_length=25, null=True)),
                ('tvc_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.people')),
                ('tvc_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_notes', models.CharField(max_length=100, null=True)),
                ('streaming_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.network')),
                ('streaming_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
    ]
