# Generated by Django 3.2.3 on 2021-06-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_alter_tvshow_tv_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisode',
            name='epi_air_date',
            field=models.DateField(null=True),
        ),
    ]
