# Generated by Django 3.2.3 on 2021-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_tvepisode_epi_air_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='tv_year',
            field=models.CharField(max_length=20),
        ),
    ]
