# Generated by Django 3.2.3 on 2021-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_alter_tvshow_tv_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='tv_next_epi',
            field=models.DateField(default='2021-03-03'),
            preserve_default=False,
        ),
    ]
