# Generated by Django 3.2.3 on 2021-06-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0005_tvshow_tv_next_epi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeason',
            fields=[
                ('tvs_sid', models.AutoField(primary_key=True, serialize=False)),
                ('tvs_air_date', models.DateField(null=True)),
                ('tvs_sno', models.CharField(max_length=2)),
                ('tvs_epicount', models.IntegerField(null=True)),
                ('tvs_desc', models.TextField(null=True)),
                ('tvs_poster', models.CharField(max_length=400, null=True)),
                ('tvs_sname', models.CharField(max_length=20)),
                ('tve_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
    ]
