# Generated by Django 3.2.3 on 2021-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0006_tvseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='tv_next_epi',
            field=models.DateField(null=True),
        ),
    ]
