# Generated by Django 3.2.3 on 2021-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0007_alter_tvshow_tv_next_epi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='tv_creator',
            field=models.CharField(max_length=100),
        ),
    ]
