# Generated by Django 3.2.3 on 2021-06-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_slug', models.CharField(max_length=200)),
                ('movie_release', models.DateTimeField(null=True)),
                ('movie_imdb', models.FloatField(null=True)),
                ('movie_rt', models.IntegerField(null=True)),
                ('movie_rating', models.CharField(max_length=3)),
                ('movie_popularity', models.FloatField(null=True)),
                ('movie_desc', models.TextField(null=True)),
                ('movie_runtime', models.IntegerField(null=True)),
                ('movie_yt', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['movie_title'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('people_id', models.IntegerField(primary_key=True, serialize=False)),
                ('people_name', models.CharField(max_length=200)),
                ('people_slug', models.CharField(max_length=220)),
                ('people_gender', models.CharField(max_length=2)),
                ('people_desc', models.TextField(null=True)),
                ('people_profession', models.CharField(max_length=20)),
                ('people_dob', models.DateField(null=True)),
                ('people_img', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('studio_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=100)),
                ('studio_slug', models.CharField(max_length=120)),
                ('studio_area', models.CharField(max_length=30)),
                ('studio_hq', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mg_genre', models.CharField(max_length=20)),
                ('mg_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_role', models.CharField(max_length=60)),
                ('mc_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('mc_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.people')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_char', models.CharField(max_length=40)),
                ('mc_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('mc_star', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.people')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.people'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.studio'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=30)),
                ('movie_rating', models.CharField(max_length=3)),
                ('issue_authority', models.CharField(max_length=50)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
