# Generated by Django 3.2.3 on 2021-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_people_people_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_gender',
            field=models.CharField(max_length=6),
        ),
    ]
