# Generated by Django 3.2.3 on 2021-06-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_people_people_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['people_name']},
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('award_id', models.IntegerField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=100)),
                ('award_category', models.CharField(max_length=50)),
                ('award_status', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('authority', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.people')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
