# Generated by Django 3.2.3 on 2021-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210617_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_awards',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
