# Generated by Django 3.2.3 on 2021-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_movie_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(null=True),
        ),
    ]
