# Generated by Django 3.2.3 on 2021-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_runtime',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
