# Generated by Django 3.2.3 on 2021-06-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.studio'),
        ),
    ]
