# Generated by Django 3.2.3 on 2021-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
