# Generated by Django 3.2.3 on 2021-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20210617_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
