# Generated by Django 3.2.3 on 2021-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
