# Generated by Django 3.2.3 on 2021-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_remove_movie_movie_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='mc_char',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
