# Generated by Django 3.2.3 on 2021-06-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_moviecast_mc_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
