# Generated by Django 3.2.3 on 2021-06-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_movie_movie_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
