# Generated by Django 3.2.3 on 2021-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_delete_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_imdb',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_rt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
